### ISSUE TITLE
wreq-0.5.4.4 fails to build

### ISSUE THREAD

**Issue by Abbath** [bos/wreq#164]
wreq-0.5.4.4 fails to build with GHC 9.6.7
```
Network/Wreq/Internal/AWS.hs:135:17: error: [GHC-39999]
    • No instance for ‘memory-0.18.0:Data.ByteArray.Types.ByteArrayAccess
                         (CT.Digest CT.SHA256)’
        arising from a use of ‘convert’
    • In the expression: convert (hmacGetDigest h)
      In an equation for ‘hmac'’:
          hmac' s k
            = convert (hmacGetDigest h)
            where
                h = hmac k s :: (HMAC CT.SHA256)
      In an equation for ‘signRequestV4’:
          signRequestV4 key secret serviceRegion request
            = do !ts <- timestamp
                 let origHost = ...
                     ....
                 let encodePath p = ...
                 ....
            where
                lowerCI = S.map toLower . CI.original
                trimHeaderValue = id
                timestamp
                  = render <$> getCurrentTime
                  where
                      render
                        = S.pack
                            . formatTime defaultTimeLocale "%Y%m%dT%H%M%SZ"
                                . utcToLocalTime utc
                hmac' :: S.ByteString -> S.ByteString -> S.ByteString
                ....
    |
135 |     hmac' s k = convert (hmacGetDigest h)
    |                 ^^^^^^^
```

**Comment by ondrap** [comment]
I forgot to upload the 0.5.4.5 to hackage - just did that, can you try that version?

**Comment by Abbath** [comment]
0.5.4.5 fixed it.
